import sqlite3

conn = sqlite3.connect('database/palavras.db')
c = conn.cursor()

novas_palavras = [ 
    ("árvore", "Produz oxigênio e sombra, essencial para a vida."),
    ("água", "Fonte de vida, beba bastante para se hidratar."),
    ("casa", "Seu lar, onde você encontra conforto e segurança."),
    ("sol", "Estrela que ilumina a Terra e nos aquece."),
    ("lua", "Satélite natural que brilha no céu noturno."),
    ("estrela", "Pontos luminosos no céu, distantes e fascinantes."),
    ("flor", "Parte colorida da planta, geralmente perfumada."),
    ("fruta", "Alimento saudável, rico em vitaminas."),
    ("pão", "Alimento básico, feito de farinha e água."),
    ("leite", "Bebida nutritiva, especialmente para crianças."),
    ("carro", "Meio de transporte popular, para se locomover."),
    ("moto", "Veículo de duas rodas, ágil no trânsito."),
    ("ônibus", "Transporte público, ideal para grandes grupos."),
    ("trem", "Transporte ferroviário, bom para longas distâncias."),
    ("avião", "Meio de transporte aéreo, rápido para viajar."),
    ("barco", "Transporte aquático, para navegar em rios ou mares."),
    ("bicicleta", "Ótima para se exercitar e se deslocar."),
    ("sapato", "Calçado para proteger os pés."),
    ("meia", "Peça de vestuário para os pés, usada com sapatos."),
    ("calça", "Peça de roupa para as pernas."),
    ("camisa", "Peça de roupa para a parte superior do corpo."),
    ("vestido", "Peça única de roupa feminina."),
    ("saia", "Peça de roupa feminina para a parte inferior do corpo."),
    ("chapéu", "Acessório para proteger a cabeça."),
    ("óculos", "Acessório para melhorar a visão ou proteger os olhos."),
    ("relógio", "Instrumento para medir o tempo."),
    ("anel", "Joia usada no dedo."),
    ("brinco", "Joia usada na orelha."),
    ("colar", "Joia usada no pescoço."),
    ("pulseira", "Joia usada no pulso."),
    ("espelho", "Objeto que reflete a imagem."),
    ("chave", "Objeto para abrir fechaduras."),
    ("porta", "Abertura para entrar ou sair de um local."),
    ("janela", "Abertura para entrada de luz e ar."),
    ("parede", "Estrutura vertical que delimita um espaço."),
    ("teto", "Parte superior de um cômodo."),
    ("chão", "Superfície onde pisamos."),
    ("mesa", "Móvel com tampo para apoiar objetos."),
    ("cadeira", "Móvel para sentar."),
    ("sofá", "Móvel acolchoado para sentar ou deitar."),
    ("cama", "Móvel para dormir."),
    ("guarda", "Ato de proteger ou guardar algo."),
    ("armário", "Móvel para guardar roupas ou objetos."),
    ("prato", "Utensílio para servir alimentos."),
    ("copo", "Utensílio para beber líquidos."),
    ("talher", "Conjunto de garfo, faca e colher."),
    ("panela", "Utensílio para cozinhar alimentos."),
    ("fogão", "Eletrodoméstico para cozinhar."),
    ("forno", "Compartimento para assar ou aquecer alimentos."),
    ("geladeira", "Eletrodoméstico para refrigerar alimentos."),
    ("microondas", "Eletrodoméstico para aquecer alimentos rapidamente."),
    ("televisão", "Aparelho para assistir a programas e filmes."),
    ("rádio", "Aparelho para ouvir música e notícias."),
    ("telefone", "Aparelho para comunicação à distância."),
    ("computador", "Máquina eletrônica para processar dados."),
    ("notebook", "Computador portátil."),
    ("tablet", "Dispositivo eletrônico com tela sensível ao toque."),
    ("celular", "Telefone móvel, essencial hoje em dia."),
    ("mouse", "Dispositivo de entrada para computadores."),
    ("teclado", "Dispositivo para digitar em computadores."),
    ("monitor", "Tela de um computador."),
    ("impressora", "Máquina para imprimir documentos."),
    ("câmera", "Aparelho para tirar fotos e gravar vídeos."),
    ("livro", "Obra escrita para leitura."),
    ("caneta", "Instrumento para escrever com tinta."),
    ("lápis", "Instrumento para escrever ou desenhar."),
    ("borracha", "Objeto para apagar o que foi escrito a lápis."),
    ("papel", "Material para escrever ou imprimir."),
    ("caderno", "Conjunto de folhas de papel para anotações."),
    ("mochila", "Bolsa para carregar objetos nas costas."),
    ("mala", "Bolsa grande para viagens."),
    ("carteira", "Objeto para guardar dinheiro e documentos."),
    ("dinheiro", "Meio de troca para bens e serviços."),
    ("moeda", "Pequena peça metálica usada como dinheiro."),
    ("nota", "Papel-moeda, valor maior que a moeda."),
    ("cartão", "Meio de pagamento eletrônico."),
    ("banco", "Instituição financeira."),
    ("loja", "Estabelecimento comercial."),
    ("mercado", "Local para comprar alimentos e outros produtos."),
    ("escola", "Local de ensino e aprendizado."),
    ("sala", "Cômodo de uma casa ou escola."),
    ("aluno", "Pessoa que estuda."),
    ("professor", "Pessoa que ensina."),
    ("quadro", "Superfície para escrever ou desenhar na sala de aula."),
    ("giz", "Material usado para escrever no quadro-negro."),
    ("caneta", "Instrumento para escrever em quadro branco."),
    ("apagador", "Objeto para apagar o quadro."),
    ("biblioteca", "Local para ler e pegar livros emprestados."),
    ("parque", "Área verde para lazer e recreação."),
    ("praça", "Espaço público com bancos e vegetação."),
    ("rua", "Via pública para tráfego de veículos e pedestres."),
    ("avenida", "Rua larga e importante."),
    ("calçada", "Área para pedestres ao lado da rua."),
    ("semáforo", "Sinal de trânsito para regular o fluxo."),
    ("placa", "Sinalização de trânsito ou identificação."),
    ("poste", "Suporte para fios elétricos ou iluminação."),
    ("lâmpada", "Dispositivo que produz luz."),
    ("cabo", "Fio elétrico ou de comunicação."),
    ("tomada", "Ponto de energia elétrica."),
    ("pilha", "Fonte de energia portátil para aparelhos."),
    ("bateria", "Fonte de energia recarregável."),
    ("carregador", "Dispositivo para carregar baterias."),
    ("fone", "Aparelho para ouvir áudio individualmente."),
    ("caixa", "Recipiente para guardar ou transportar objetos."),
    ("mala", "Bolsa grande para viagens."),
    ("bolsa", "Acessório para carregar objetos pessoais."),
    ("cinto", "Acessório para prender a calça na cintura."),
    ("gravata", "Acessório masculino usado no pescoço."),
    ("lenço", "Pedaço de tecido para limpar ou enfeitar."),
    ("luva", "Peça de vestuário para as mãos."),
    ("cachecol", "Acessório de lã ou tecido para o pescoço."),
    ("gorro", "Chapéu de lã para proteger do frio."),
    ("chuva", "Água que cai do céu."),
    ("neve", "Água congelada que cai do céu."),
    ("vento", "Movimento do ar."),
    ("nuvem", "Massa visível de vapor d'água no céu."),
    ("trovão", "Ruído forte que acompanha o raio."),
    ("raio", "Descarga elétrica na atmosfera."),
    ("relâmpago", "Flash de luz de uma tempestade."),
    ("clima", "Condições meteorológicas de um lugar."),
    ("tempo", "Condições atmosféricas atuais."),
    ("estação", "Divisão do ano (verão, inverno, etc.)."),
    ("verão", "Estação mais quente do ano."),
    ("inverno", "Estação mais fria do ano."),
    ("primavera", "Estação das flores."),
    ("outono", "Estação da queda das folhas."),
    ("campo", "Área rural, oposto à cidade."),
    ("montanha", "Grande elevação de terra."),
    ("rio", "Curso de água natural."),
    ("lago", "Grande corpo de água cercado por terra."),
    ("mar", "Grande extensão de água salgada."),
    ("praia", "Área de areia junto ao mar."),
    ("onda", "Movimento da água do mar."),
    ("areia", "Pequenos grãos de rocha na praia."),
    ("concha", "Invólucro de moluscos marinhos."),
    ("peixe", "Animal aquático com brânquias."),
    ("ave", "Animal com penas e asas."),
    ("inseto", "Pequeno animal com seis pernas."),
    ("aranha", "Aracnídeo com oito pernas."),
    ("formiga", "Pequeno inseto que vive em colônias."),
    ("abelha", "Inseto que produz mel e pólen."),
    ("borboleta", "Inseto com asas coloridas."),
    ("mosquito", "Pequeno inseto que pica."),
    ("cobra", "Réptil sem pernas."),
    ("lagarto", "Réptil com escamas e quatro pernas."),
    ("sapo", "Anfíbio que vive perto da água."),
    ("rato", "Pequeno roedor."),
    ("cachorro", "Melhor amigo do homem."),
    ("gato", "Animal de estimação independente."),
    ("pássaro", "Ave pequena, geralmente canta."),
    ("galinha", "Ave que bota ovos."),
    ("boi", "Animal de grande porte, usado para carne ou trabalho."),
    ("vaca", "Fêmea do boi, produz leite."),
    ("cavalo", "Animal usado para montaria e trabalho."),
    ("ovelha", "Animal que produz lã."),
    ("porco", "Animal usado para carne."),
    ("leão", "Rei da selva, grande felino."),
    ("tigre", "Felino listrado, grande e forte."),
    ("elefante", "Maior animal terrestre."),
    ("macaco", "Animal com habilidades de escalada."),
    ("zebra", "Animal africano com listras."),
    ("girafa", "Animal com pescoço longo."),
    ("urso", "Animal grande e peludo."),
    ("lobo", "Animal selvagem, vive em matilha."),
    ("raposa", "Animal astuto e solitário."),
    ("cervo", "Animal com chifres ramificados."),
    ("coelho", "Animal pequeno e saltitante."),
    ("pato", "Ave aquática."),
    ("cisne", "Ave aquática elegante."),
    ("baleia", "Maior mamífero marinho."),
    ("tubarão", "Peixe grande e predador."),
    ("golfinho", "Mamífero marinho inteligente."),
    ("tartaruga", "Réptil com carapaça protetora."),
    ("caranguejo", "Crustáceo com pinças."),
    ("polvo", "Molusco com oito braços."),
    ("estrela", "Corpo celeste que brilha no céu."),
    ("planeta", "Corpo celeste que orbita uma estrela."),
    ("terra", "Nosso planeta."),
    ("marte", "Planeta vermelho."),
    ("júpiter", "Maior planeta do sistema solar."),
    ("saturno", "Planeta com anéis."),
    ("urano", "Planeta azul-esverdeado."),
    ("netuno", "Planeta azul escuro."),
    ("plutão", "Planeta anão."),
    ("sol", "Estrela central do sistema solar."),
    ("universo", "Tudo o que existe."),
    ("galáxia", "Sistema de estrelas, gás e poeira."),
    ("buraco", "Abertura ou espaço vazio."),
    ("cometa", "Corpo celeste com cauda luminosa."),
    ("meteoro", "Rocha espacial que entra na atmosfera."),
    ("rocha", "Material sólido da crosta terrestre."),
    ("minério", "Rocha que contém metais."),
    ("cristal", "Sólido com estrutura molecular regular."),
    ("metal", "Substância com brilho e condutividade."),
    ("ouro", "Metal precioso, amarelo e brilhante."),
    ("prata", "Metal precioso, branco e brilhante."),
    ("cobre", "Metal avermelhado, bom condutor."),
    ("ferro", "Metal comum, usado em construções."),
    ("aço", "Liga de ferro e carbono, muito resistente."),
    ("plástico", "Material sintético, leve e versátil."),
    ("vidro", "Material transparente e frágil."),
    ("madeira", "Material da árvore, usado em construções."),
    ("tijolo", "Material de construção, feito de argila."),
    ("cimento", "Material aglomerante para construções."),
    ("argila", "Terra fina e pegajosa, usada em cerâmica."),
    ("areia", "Pequenos grãos de rocha."),
    ("água", "Substância essencial para a vida."),
    ("gás", "Substância em estado gasoso."),
    ("líquido", "Substância que flui livremente."),
    ("sólido", "Substância com forma e volume definidos."),
    ("energia", "Capacidade de realizar trabalho."),
    ("força", "Ação que causa ou impede movimento."),
    ("movimento", "Mudança de posição."),
    ("velocidade", "Rapidez do movimento."),
    ("tempo", "Duração de eventos."),
    ("espaço", "Extensão ilimitada no qual os objetos existem."),
    ("peso", "Força da gravidade sobre um objeto."),
    ("massa", "Quantidade de matéria em um objeto."),
    ("volume", "Quantidade de espaço que um objeto ocupa."),
    ("temperatura", "Medida de calor ou frio."),
    ("calor", "Energia térmica."),
    ("frio", "Ausência de calor."),
    ("luz", "Radiação eletromagnética visível."),
    ("sombra", "Área escura causada pela ausência de luz."),
    ("cor", "Propriedade da luz refletida ou emitida."),
    ("som", "Vibração que se propaga e pode ser ouvida."),
    ("silêncio", "Ausência de som."),
    ("cheiro", "Sensação olfativa."),
    ("sabor", "Sensação gustativa."),
    ("toque", "Sensação tátil."),
    ("visão", "Sentido da vista."),
    ("audição", "Sentido do ouvido."),
    ("olfato", "Sentido do cheiro."),
    ("paladar", "Sentido do sabor."),
    ("tato", "Sentido do toque."),
    ("sentido", "Capacidade de perceber estímulos."),
    ("cérebro", "Órgão principal do sistema nervoso."),
    ("mente", "Conjunto de faculdades intelectuais e psíquicas."),
    ("corpo", "Organismo de um ser vivo."),
    ("coração", "Órgão que bombeia sangue."),
    ("pulmão", "Órgão para respiração."),
    ("estômago", "Órgão da digestão."),
    ("fígado", "Órgão que filtra o sangue."),
    ("rim", "Órgão que filtra o sangue e produz urina."),
    ("osso", "Estrutura rígida do esqueleto."),
    ("músculo", "Tecido que permite o movimento."),
    ("pele", "Revestimento externo do corpo."),
    ("cabelo", "Fios que crescem na cabeça."),
    ("olho", "Órgão da visão."),
    ("nariz", "Órgão do olfato."),
    ("boca", "Abertura para comer e falar."),
    ("língua", "Órgão do paladar e da fala."),
    ("dente", "Estrutura óssea na boca."),
    ("orelha", "Órgão da audição."),
    ("mão", "Parte do corpo com dedos."),
    ("pé", "Extremidade da perna para andar."),
    ("dedo", "Extensão da mão ou do pé."),
    ("braço", "Membro superior do corpo."),
    ("perna", "Membro inferior do corpo."),
    ("cabeça", "Parte superior do corpo."),
    ("pescoço", "Parte que une a cabeça ao tronco."),
    ("tronco", "Corpo sem cabeça, braços e pernas."),
    ("costas", "Parte posterior do tronco."),
    ("barriga", "Abdômen."),
    ("ombro", "Articulação entre o braço e o tronco."),
    ("joelho", "Articulação da perna."),
    ("cotovelo", "Articulação do braço."),
    ("pulso", "Articulação da mão."),
    ("tornozelo", "Articulação do pé."),
    ("rosto", "Parte frontal da cabeça."),
    ("narina", "Abertura do nariz."),
    ("lábio", "Parte externa da boca."),
    ("queixo", "Parte inferior do rosto."),
    ("testa", "Parte superior do rosto."),
    ("sobrancelha", "Pelos acima dos olhos."),
    ("cílio", "Pelos na borda da pálpebra."),
    ("bochecha", "Parte lateral do rosto."),
    ("sorriso", "Expressão facial de alegria."),
    ("risada", "Som de alegria."),
    ("choro", "Lágrimas de tristeza."),
    ("medo", "Sentimento de apreensão ou pavor."),
    ("raiva", "Sentimento de ira ou indignação."),
    ("alegria", "Sentimento de felicidade."),
    ("tristeza", "Sentimento de infelicidade."),
    ("amor", "Sentimento de afeto profundo."),
    ("ódio", "Sentimento de aversão intensa."),
    ("paz", "Estado de tranquilidade."),
    ("guerra", "Conflito armado."),
    ("amigo", "Pessoa com quem se tem amizade."),
    ("família", "Grupo de pessoas unidas por parentesco."),
    ("pai", "Genitor masculino."),
    ("mãe", "Genitora feminina."),
    ("irmão", "Filho dos mesmos pais."),
    ("irmã", "Filha dos mesmos pais."),
    ("filho", "Descendente masculino."),
    ("filha", "Descendente feminina."),
    ("avô", "Pai do pai ou da mãe."),
    ("avó", "Mãe do pai ou da mãe."),
    ("tio", "Irmão do pai ou da mãe."),
    ("tia", "Irmã do pai ou da mãe."),
    ("primo", "Filho do tio ou da tia."),
    ("prima", "Filha do tio ou da tia."),
    ("vizinho", "Pessoa que mora perto."),
    ("colega", "Pessoa que trabalha ou estuda junto."),
    ("chefe", "Pessoa que lidera um grupo ou empresa."),
    ("cliente", "Pessoa que compra produtos ou serviços."),
    ("vendedor", "Pessoa que vende."),
    ("comprador", "Pessoa que compra."),
    ("trabalho", "Atividade produtiva."),
    ("emprego", "Ocupação remunerada."),
    ("salário", "Remuneração pelo trabalho."),
    ("feriado", "Dia de descanso oficial."),
    ("férias", "Período de descanso do trabalho."),
    ("viagem", "Deslocamento para outro local."),
    ("hotel", "Local para hospedagem."),
    ("aeroporto", "Local de partida e chegada de aviões."),
    ("rodoviária", "Local de partida e chegada de ônibus."),
    ("porto", "Local de partida e chegada de navios."),
    ("museu", "Local para exibição de arte e história."),
    ("teatro", "Local para apresentações artísticas."),
    ("cinema", "Local para assistir filmes."),
    ("concerto", "Apresentação musical."),
    ("festa", "Celebração social."),
    ("dança", "Arte de mover o corpo ao ritmo da música."),
    ("música", "Arte de combinar sons."),
    ("canto", "Ato de cantar."),
    ("leitura", "Hábito de ler."),
    ("escrita", "Ato de escrever."),
    ("desenho", "Representação visual de algo."),
    ("pintura", "Arte de usar tintas para criar imagens."),
    ("escultura", "Arte de moldar formas em três dimensões."),
    ("fotografia", "Arte de capturar imagens com luz."),
    ("filme", "Obra audiovisual."),
    ("televisão", "Aparelho para assistir programas."),
    ("rádio", "Meio de comunicação sonora."),
    ("jornal", "Publicação de notícias."),
    ("revista", "Publicação periódica com artigos e imagens."),
    ("notícia", "Informação sobre eventos recentes."),
    ("reportagem", "Matéria jornalística detalhada."),
    ("entrevista", "Conversa para obter informações."),
    ("comunicação", "Processo de transmitir informações."),
    ("linguagem", "Sistema de comunicação."),
    ("palavra", "Unidade de significado na linguagem."),
    ("frase", "Conjunto de palavras com sentido completo."),
    ("texto", "Conjunto de frases."),
    ("livro", "Obra escrita para leitura."),
    ("dicionário", "Livro com significados de palavras."),
    ("enciclopédia", "Obra com informações sobre diversos temas."),
    ("gramática", "Estudo das regras de uma língua."),
    ("literatura", "Obras escritas de valor artístico."),
    ("poesia", "Arte de expressar sentimentos em versos."),
    ("prosa", "Linguagem escrita ou falada sem rima."),
    ("história", "Estudo do passado."),
    ("geografia", "Estudo da Terra e seus habitantes."),
    ("matemática", "Estudo de números e formas."),
    ("física", "Estudo da matéria e energia."),
    ("química", "Estudo da composição da matéria."),
    ("biologia", "Estudo dos seres vivos."),
    ("ciência", "Busca de conhecimento através de métodos."),
    ("descoberta", "Ato de encontrar algo novo."),
    ("invenção", "Criação de algo inédito."),
    ("inovação", "Introdução de algo novo ou melhorado."),
    ("pesquisa", "Investigação para descobrir fatos."),
    ("estudo", "Atividade de aprender."),
    ("conhecimento", "Informações e habilidades adquiridas."),
    ("sabedoria", "Aplicação do conhecimento."),
    ("inteligência", "Capacidade de aprender e aplicar conhecimento."),
    ("talento", "Habilidade natural."),
    ("habilidade", "Capacidade de fazer algo bem."),
    ("prática", "Exercício para melhorar habilidades."),
    ("treino", "Preparação para uma atividade."),
    ("esporte", "Atividade física competitiva."),
    ("jogo", "Atividade recreativa com regras."),
    ("competição", "Disputa para determinar um vencedor."),
    ("vitória", "Ato de vencer."),
    ("derrota", "Ato de perder."),
    ("regra", "Princípio que governa o comportamento."),
    ("lei", "Sistema de regras que regulam o comportamento."),
    ("justiça", "Princípio de imparcialidade."),
    ("punição", "Consequência de uma infração."),
    ("crime", "Ato ilegal."),
    ("pena", "Punição por um crime."),
    ("júri", "Grupo que decide em um tribunal."),
    ("juiz", "Oficial que preside um tribunal."),
    ("advogado", "Profissional do direito."),
    ("promotor", "Acusador em um tribunal."),
    ("polícia", "Força de segurança pública."),
    
    ('python', 'Linguagem de programação'),
    ('flask', 'Framework web em Python'),
    # mais palavras aqui
]
palavras_dificeis = [
    ('egrégio', 'Usado para tratar alguém com grande respeito', 'dificil'),
    ('enfadonho', 'Muito chato, que causa tédio', 'dificil'),
    ('escarcéu', 'Barulho e confusão exagerados', 'dificil'),
    ('enlevado', 'Profundamente encantado', 'dificil'),
    ('esdrúxulo', 'Muito estranho ou fora do comum', 'dificil'),
    ('esbulho', 'Ato de tomar algo de forma injusta', 'dificil'),
    ('escaramuça', 'Pequeno combate ou briga rápida', 'dificil'),
    ('estultícia', 'Falta de inteligência ou bom senso', 'dificil'),
    ('empertigado', 'Muito rígido ou orgulhoso na postura', 'dificil'),
    ('esbaforido', 'Ofegante, sem fôlego por esforço', 'dificil'),
    ('exaurido', 'Totalmente cansado, esgotado', 'dificil'),
    ('estro', 'Inspiração criativa, geralmente poética', 'dificil'),
    ('esotérico', 'Misterioso, compreendido por poucos', 'dificil'),
    ('empedernido', 'Insensível, teimosamente endurecido', 'dificil'),
    ('enfezado', 'Irritado, com raiva', 'dificil'),
    ('epíteto', 'Palavra que caracteriza algo ou alguém', 'dificil'),
    ('enlace', 'Ligação afetiva ou união amorosa', 'dificil'),
    ('espectro', 'Aparição fantasmagórica', 'dificil'),
    ('esfacelar', 'Despedaçar, destruir completamente', 'dificil'),
    ('exegese', 'Interpretação crítica de texto, especialmente religioso', 'dificil'),
    ('fétido', 'Com cheiro muito desagradável', 'dificil'),
    ('falácia', 'Raciocínio falso com aparência de verdade', 'dificil'),
    ('fustigar', 'Castigar com golpes ou palavras', 'dificil'),
    ('fidalgo', 'Nobre, pessoa de alta linhagem', 'dificil'),
    ('frenesi', 'Excitação extrema ou agitação', 'dificil'),
    ('fidedigno', 'Confiável, digno de fé', 'dificil'),
    ('fanal', 'Fonte de luz, como farol', 'dificil'),
    ('filigrana', 'Trabalho delicado em metal precioso', 'dificil'),
    ('fulgurar', 'Brilhar intensamente', 'dificil'),
    ('formidável', 'Que causa admiração ou medo', 'dificil'),
    ('faina', 'Trabalho intenso ou cansativo', 'dificil'),
    ('gélido', 'Extremamente frio', 'dificil'),
    ('gáudio', 'Alegria intensa', 'dificil'),
    ('gregário', 'Que vive em grupo', 'dificil'),
    ('granítico', 'Muito duro, inflexível como granito', 'dificil'),
    ('grosseiro', 'Bruto, sem delicadeza', 'dificil'),
    ('gáudio', 'Alegria intensa, júbilo', 'dificil'),
    ('garrido', 'Vistoso, com cores alegres', 'dificil'),
    ('glacial', 'Extremamente frio, como gelo', 'dificil'),
    ('genuíno', 'Autêntico, verdadeiro', 'dificil'),
    ('hilário', 'Muito engraçado', 'dificil'),
    ('hipérbole', 'Exagero usado como figura de linguagem', 'dificil'),
    ('hercúleo', 'Que exige muita força ou esforço', 'dificil'),
    ('hediondo', 'Extremamente horrível ou repulsivo', 'dificil'),
    ('hierático', 'Solene, impenetrável, como uma estátua', 'dificil'),
    ('hesitante', 'Que demonstra indecisão', 'dificil'),
    ('harém', 'Conjunto de esposas ou concubinas', 'dificil'),
    ('ignóbil', 'Sem honra, vil', 'dificil'),
    ('idílico', 'Muito bonito e calmo, como em um sonho', 'dificil'),
    ('impávido', 'Sem medo, corajoso', 'dificil'),
    ('inócuo', 'Que não causa dano', 'dificil'),
    ('inóspito', 'Inabitável, difícil de viver', 'dificil'),
    ('insólito', 'Raro, incomum', 'dificil'),
    ('ignóbil', 'De má índole, desprezível', 'dificil'),
    ('incólume', 'Ileso, sem ferimentos', 'dificil'),
    ('lascívia', 'Desejo sexual intenso', 'dificil'),
    ('lânguido', 'Sem energia, fraco', 'dificil'),
    ('labiríntico', 'Cheio de caminhos confusos', 'dificil'),
    ('lenitivo', 'Que acalma ou alivia', 'dificil'),
    ('liturgia', 'Conjunto de ritos religiosos', 'dificil'),
    ('limítrofe', 'Que faz fronteira', 'dificil'),
    ('logro', 'Engano, trapaça', 'dificil'),
    ('lacônico', 'Que fala pouco, de forma concisa', 'dificil'),
    ('magnânimo', 'Generoso, com grande alma', 'dificil'),
    ('moroso', 'Lento, demorado', 'dificil'),
    ('mancebo', 'Homem jovem', 'dificil'),
    ('misantropo', 'Pessoa que evita o convívio social', 'dificil'),
    ('maniqueísta', 'Que vê tudo como bem ou mal absolutos', 'dificil'),
    ('mórbido', 'Relacionado à doença ou morbidez', 'dificil'),
    ('nefasto', 'Muito ruim, trágico', 'dificil'),
    ('nômade', 'Pessoa sem residência fixa', 'dificil'),
    ('nauseante', 'Que causa enjoo', 'dificil'),
    ('nebuloso', 'Pouco claro, confuso', 'dificil'),
    ('nítido', 'Claro, distinto', 'dificil'),
    ('obnóxio', 'Sujeito a punição ou crítica', 'dificil'),
    ('oneroso', 'Que causa gastos, custoso', 'dificil'),
    ('obsequioso', 'Excessivamente prestativo', 'dificil'),
    ('obtuso', 'Pouco inteligente ou lento para entender', 'dificil'),
    ('omisso', 'Que se abstém de agir', 'dificil'),
    ('pérfido', 'Traiçoeiro, desleal', 'dificil'),
    ('pusilânime', 'Covarde, sem coragem', 'dificil'),
    ('perdulário', 'Que gasta em excesso', 'dificil'),
    ('patente', 'Claro, evidente', 'dificil'),
    ('pernóstico', 'Afetado, pretensioso', 'dificil'),
    ('precípuo', 'Principal, essencial', 'dificil'),
    ('quimera', 'Ilusão, sonho impossível', 'dificil'),
    ('quixotesco', 'Idealista e ingênuo', 'dificil'),
    ('querela', 'Discussão judicial', 'dificil'),
    ('quinquênio', 'Período de cinco anos', 'dificil'),
    ('quidam', 'Pessoa desconhecida, qualquer um', 'dificil'),
    ('recalcitrante', 'Teimoso, resistente', 'dificil'),
    ('reticente', 'Que hesita ou evita dizer tudo', 'dificil'),
    ('ranzinza', 'Mal-humorado, rabugento', 'dificil'),
    ('resignado', 'Que aceita sem reclamar', 'dificil'),
    ('reverberar', 'Refletir luz ou som', 'dificil'),
    ('sagaz', 'Perspicaz, inteligente', 'dificil'),
    ('soturno', 'Triste, sombrio', 'dificil'),
    ('sibilante', 'Com som agudo, como assobio', 'dificil'),
    ('suscetível', 'Sensível, facilmente afetado', 'dificil'),
    ('sagacidade', 'Capacidade de perceber com clareza', 'dificil'),
    ('solilóquio', 'Fala consigo mesmo', 'dificil'),
    ('sapiência', 'Sabedoria profunda', 'dificil'),
    ('subterfúgio', 'Desculpa para escapar de algo', 'dificil'),
    ('supérfluo', 'Desnecessário, em excesso', 'dificil'),
    ('sórdido', 'Sujo, moralmente repulsivo', 'dificil'),
    ('singeleza', 'Qualidade do que é simples e puro', 'dificil'),
    ('salutar', 'Benéfico à saúde', 'dificil'),
    ('síntese', 'Resumo, combinação de ideias', 'dificil')
]


c.executemany('INSERT INTO palavras (palavra, dica, nivel) VALUES (?, ?, ?)', palavras_dificeis)


conn.commit()
conn.close()

print('Novas palavras adicionadas!')
